### ISSUE TITLE
allow using custom adapters

### ISSUE THREAD

**Issue by ghost** [johnhamelink/sms_blitz#6]
Right now they [are hardcoded in a map](https://github.com/johnhamelink/sms_blitz/blob/9815f3e9467052ebf9edfd76cae1d678ab15ce46/lib/sms_blitz.ex#L5-L10), it seems. I want be able to add new adapters by providing a module which implements the sms_blitz.adapter behaviour.

What I want to do is:

```elixir
SmsBlitz.send_sms(MyApp.SMS.LocalAdapter, sms_params) # -> Logger.debug(... sms_params ...)
SmsBlitz.send_sms(MyApp.SMS.TestAdapter, sms_params) # -> send(test_pid, {:sms, sms_params})
```

**Comment by ghost** [comment]
The easiest way to accomplish this while not breaking existing code is to make the "adapters" map configurable:

```elixir
config :sms_blitz, adapters: %{twilio: SmsBlitz.Twilio, local: MyApp.SMS.LocalAdapter, ...}
```
or
```elixir
config :sms_blitz, extra_adapters: %{local: MyApp.SMS.LocalAdapter, ...}
```

Then I'd be able to do something like

```elixir
SmsBlitz.send_sms(:local, sms_params)
```

I can open a PR if you are interested.

**Comment by johnhamelink** [comment]
Please do open a PR. A more modular design would be very useful for building new adapters as well.
